version: 2

sources:
  - name: AZURE_RAW
    database: CT_JAYANT_PANDEY_DB
    schema: AZURE_RAW
    config:
      loaded_at_field: METADATA$FILE_LAST_MODIFIED
      freshness:
        warn_after:
          count: 1
          period: day
        error_after:
          count: 135
          period: day
    tables:
      - name: customer_ext
        description: "External table for customer JSON data."
      - name: employee_ext
        description: "External table for employee JSON data."
      - name: orders_ext
        description: "External table for orders JSON data."
      - name: product_ext
        description: "External table for product JSON data."
        config:
          loaded_at_field: METADATA$FILE_LAST_MODIFIED
          freshness:
            warn_after:
              count: 10
              period: day
            error_after:
              count: 200
              period: day
      - name: store_ext
        description: "External table for store JSON data."